### ISSUE TITLE
Fejl ved Create User 

### ISSUE THREAD

**Issue by TCAA-Web** [Webudvikler-TechCollege/stringsonline_api#2]
Når man kalder Create User får man dette svar: 

"message": "Could not create record: SequelizeValidationError: notNull Violation: user.address cannot be null,\nnotNull Violation: user.zipcode cannot be null,\nnotNull Violation: user.city cannot be null,\nnotNull Violation: user.country_id cannot be null"

Tilføjer man: address, zipcode, city og country_id kan man godt oprette en bruger, men dette fremgår ikke i dokumentationen

**Comment by Webudvikler-TechCollege** [comment]
Bug er fikset i Postman
