### ISSUE TITLE
Fejl i Create User med active parameter

### ISSUE THREAD

**Issue by TCAA-Web** [Webudvikler-TechCollege/stringsonline_api#3]
Under create user skal man ændre **active** til **is_active**. 

Man kan godt oprette en bruger med **active** som det er angivet i dokumentationen, men kan ikke logge ind. Opretter man en ny bruger med is_active parameteret kan man godt logge ind.

**Comment by Webudvikler-TechCollege** [comment]
Bug fikset i Postman
