### ISSUE TITLE
Fejl i dokumentation ved opret anmeldelse

### ISSUE THREAD

**Issue by TCAA-Web** [Webudvikler-TechCollege/stringsonline_api#4]
Når man opretter en ny anmeldelse er det angivet i dokumentationen at man skal bruge org_id. 
Dette parameter skal laves om til product_id for at kaldet virker.

**Comment by Webudvikler-TechCollege** [comment]
Bug fikset i postman - tjek lige at det er med ud i den online dokumentation.
