### ISSUE TITLE
Fejl i review.controller.js

### ISSUE THREAD

**Issue by TCAA-Web** [Webudvikler-TechCollege/stringsonline_api#5]
Inde i review.controller (linje 24) er der et tjek efter org_id, men denne variabel er ikke defineret og får serveren til at crashe. 
Skal nok være product_id istedet. 
Ligeledes skal den også ændres fra org_id i routeren til product_id på linje 52 i main router.

**Comment by Webudvikler-TechCollege** [comment]
Bug er fikset :)
