### ISSUE TITLE
Uventet return når man ikke sender en bearer token med

### ISSUE THREAD

**Issue by TCAA-Web** [Webudvikler-TechCollege/stringsonline_api#6]
På ordrer og indkøbskurv kaldene, der kræver authentication, sender serveren en access_token tilbage når man ikke sender en med, i stedet for at sige unauthorized.

**Comment by Webudvikler-TechCollege** [comment]
Kan ikke rigtig genskabe denne fejl. Min siger Token not accepted med en 401...
