### ISSUE TITLE
Ratings findes ikke

### ISSUE THREAD

**Issue by TCAA-Web** [Webudvikler-TechCollege/stringsonline_api#7]
Ratings findes ikke i det lokale API. Der er ikke nogen ratings routes eller rating controller. 
i postman dokumentationen peger alle kald til Ratings systemet på den gamle version der ligger på api.mediehuset.net.

**Comment by Webudvikler-TechCollege** [comment]
Det ser ud til at review modulet er det nye rating modul. Der er både plads til antal stjerner og kommentar så jeg har slettet Ratings folderen fra Postman. Så skal vi lige være opmærksomme på hvad der står i opgaven.
